/** @type {import('next').NextConfig} */
const nextConfig = {
  compress: true,
  poweredByHeader: false,
  images: {
    formats: ['image/avif', 'image/webp'],
    minimumCacheTTL: 31536000,
    dangerouslyAllowSVG: true,
    contentDispositionType: 'attachment',
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
  async headers() {
    // Headers de seguranca aplicados a todas as rotas — protegem contra XSS,
    // clickjacking, sniffing e fortalecem a postura de seguranca do site.
    const securityHeaders = [
      // Forca HTTPS (HSTS) — 2 anos + subdomains. Inclui preload para a HSTS list do Chrome.
      { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
      // Bloqueia o site em iframes externos — previne clickjacking
      { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
      // Impede browsers de adivinhar MIME type — previne ataques de MIME sniffing
      { key: 'X-Content-Type-Options', value: 'nosniff' },
      // Controla qual referrer enviamos (privacidade do usuario)
      { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
      // Bloqueia features sensiveis que nao usamos
      { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=(), interest-cohort=()' },
      // CSP — permite GA4, GTM, WhatsApp, fontes Google, imagens externas usadas
      {
        key: 'Content-Security-Policy',
        value: [
          "default-src 'self'",
          "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://*.googletagmanager.com https://www.google-analytics.com https://*.google-analytics.com",
          "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
          "font-src 'self' data: https://fonts.gstatic.com",
          "img-src 'self' data: https: blob:",
          "connect-src 'self' https://www.google-analytics.com https://*.google-analytics.com https://www.googletagmanager.com https://formsubmit.co",
          "frame-src 'self' https://www.youtube.com https://www.youtube-nocookie.com",
          "frame-ancestors 'self'",
          "base-uri 'self'",
          "form-action 'self' https://formsubmit.co",
          "object-src 'none'",
          "upgrade-insecure-requests",
        ].join('; '),
      },
    ];

    return [
      {
        source: '/images/:path*',
        headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
      },
      {
        source: '/_next/static/:path*',
        headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
      },
      // Aplica headers de seguranca em TODAS as rotas (HTML, API, etc)
      {
        source: '/:path*',
        headers: securityHeaders,
      },
    ];
  },
  async redirects() {
    return [
      {
        source: '/avcb-restaurante',
        destination: '/avcb-restaurante-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-restaurantes',
        destination: '/avcb-restaurante-sao-paulo',
        permanent: true,
      },
      {
        source: '/projeto-tecnico-ocupacao-temporaria-edificacao-permanente',
        destination: '/ptotep',
        permanent: true,
      },
      {
        source: '/projeto-tecnico-para-evento',
        destination: '/ptotep',
        permanent: true,
      },
      {
        source: '/avcb-para-evento',
        destination: '/ptotep',
        permanent: true,
      },
      {
        source: '/avcb-bares-restaurantes-sao-paulo',
        destination: '/avcb-restaurante-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-bar-sao-paulo',
        destination: '/avcb-restaurante-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-bar-sao-paulo',
        destination: '/avcb-restaurante-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb',
        destination: '/avcb-sao-paulo',
        permanent: true,
      },
      {
        source: '/mapa-páginas',
        destination: '/mapa-paginas',
        permanent: true,
      },
      {
        source: '/mapa-p%C3%A1ginas',
        destination: '/mapa-paginas',
        permanent: true,
      },
      {
        source: '/avcb-para-farmacia-sao-paulo',
        destination: '/avcb-farmacia-drogaria-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-drogaria-sao-paulo',
        destination: '/avcb-farmacia-drogaria-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-boate-sao-paulo',
        destination: '/avcb-casas-noturnas-boates-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-casa-noturna-sao-paulo',
        destination: '/avcb-casas-noturnas-boates-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-bar-com-show-sao-paulo',
        destination: '/avcb-casas-noturnas-boates-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-clinica-odontologica-sao-paulo',
        destination: '/avcb-consultorios-medicos-odontologicos-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-clinica-veterinaria-sao-paulo',
        destination: '/avcb-clinica-hospital-veterinario-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-clinica-veterinaria-sao-paulo',
        destination: '/avcb-clinica-hospital-veterinario-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-hospital-veterinario-sao-paulo',
        destination: '/avcb-clinica-hospital-veterinario-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-hospital-veterinaria-sao-paulo',
        destination: '/avcb-clinica-hospital-veterinario-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-pet-shop-sao-paulo',
        destination: '/avcb-clinica-hospital-veterinario-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-estacionamento-sao-paulo',
        destination: '/avcb-estacionamento-garagem-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-estacionamento-sao-paulo',
        destination: '/avcb-estacionamento-garagem-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-garagem-sao-paulo',
        destination: '/avcb-estacionamento-garagem-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-garagem-sao-paulo',
        destination: '/avcb-estacionamento-garagem-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-estacionamento-rotativo-sao-paulo',
        destination: '/avcb-estacionamento-garagem-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-bar-adega-sao-paulo',
        destination: '/avcb-restaurante-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-salao-de-festas-sao-paulo',
        destination: '/avcb-salao-de-festas-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-hotel-sao-paulo',
        destination: '/avcb-hoteis-pousadas-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-pousada-sao-paulo',
        destination: '/avcb-hoteis-pousadas-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-pousada-sao-paulo',
        destination: '/avcb-hoteis-pousadas-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-escola-faculdade-sao-paulo',
        destination: '/avcb-para-escola-sao-paulo',
        permanent: true,
      },
      // Serviços legados → páginas dedicadas
      { source: '/servicos/chuveiro-automatico-sprinkler-sao-paulo', destination: '/sprinklers', permanent: true },
      { source: '/servicos/instalacao-hidrante-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/servicos/spda-para-raios-sao-paulo', destination: '/spda', permanent: true },
      { source: '/servicos/manutencao-sistemas-incendio', destination: '/manutencao', permanent: true },
      { source: '/servicos/projetos-seguranca-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/servicos/clcb-sao-paulo', destination: '/clcb-sao-paulo', permanent: true },
      { source: '/servicos/avcb-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/servicos/avcb-bares-restaurantes-sao-paulo', destination: '/avcb-restaurante-sao-paulo', permanent: true },
      { source: '/servicos/avcb-pousada-sao-paulo', destination: '/avcb-hoteis-pousadas-sao-paulo', permanent: true },
      { source: '/servicos/avcb-escola-faculdade-sao-paulo', destination: '/avcb-para-escola-sao-paulo', permanent: true },
      { source: '/servicos/avcb-para-drogaria-sao-paulo', destination: '/avcb-farmacia-drogaria-sao-paulo', permanent: true },
      { source: '/servicos/avcb-para-casa-noturna-sao-paulo', destination: '/avcb-casas-noturnas-boates-sao-paulo', permanent: true },
      { source: '/servicos/avcb-para-bar-com-show-sao-paulo', destination: '/avcb-casas-noturnas-boates-sao-paulo', permanent: true },
      // Brigada e preço
      { source: '/brigada', destination: '/treinamento-brigada', permanent: true },
      { source: '/avcb-preco', destination: '/quanto-custa-avcb-sao-paulo', permanent: true },
      // Edifício residencial → condomínio (mesma intenção, página customizada mais rica existe)
      { source: '/sistema-hidrante-edificio-residencial-avcb-sp', destination: '/hidrantes', permanent: true },
      // Doorway pairs — consolidação de intenção duplicada
      { source: '/sistema-hidrante-galpao-industrial-avcb-sp', destination: '/hidrantes', permanent: true },
      { source: '/sistema-alarme-incendio-galpao-industrial-avcb-sp', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-alarme-incendio-hospital-avcb-sp', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-alarme-incendio-edificio-comercial-sp', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/projeto-escada-pressurizada-avcb', destination: '/projetos-incendio', permanent: true },
      { source: '/sistema-hidrante-industria-quimica-sp', destination: '/hidrantes', permanent: true },
      { source: '/sistema-sprinkler-industria-quimica-sp', destination: '/sprinklers', permanent: true },
      // Páginas canibalizantes — consolidação de autoridade
      { source: '/alvara-bombeiro-escola-sao-paulo', destination: '/alvara-bombeiro-escola-faculdade-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-restaurante-sao-paulo', destination: '/alvara-bombeiro-bar-restaurante-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-pousada-sao-paulo', destination: '/alvara-bombeiro-hotel-pousada-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-escola-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-restaurante-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-pousada-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-condominio-sao-paulo', destination: '/avcb-para-condominio-sao-paulo', permanent: true },
      // Blog — consolidação de posts canibalizando (mesma intenção de busca)
      { source: '/blog/quanto-tempo-demora-para-emitir-o-avcb-sp', destination: '/blog/prazo-para-emissao-de-avcb', permanent: true },
      { source: '/blog/avcb-vencido-o-que-fazer-evitar-interdicao', destination: '/blog/avcb-vencido-o-que-fazer', permanent: true },
      { source: '/blog/quanto-custa-avcb-sp-precos-prazos', destination: '/blog/quanto-custa-avcb-em-sao-paulo', permanent: true },
      { source: '/blog/diferenca-entre-avcb-e-clcb-em-sao-paulo', destination: '/blog/diferenca-entre-avcb-e-clcb', permanent: true },
      { source: '/blog/avcb-x-clcb-diferenca-na-pratica', destination: '/blog/diferenca-entre-avcb-e-clcb', permanent: true },
      { source: '/blog/sprinkler-obrigatorio-sp', destination: '/blog/sprinkler-obrigatorio-para-quem-e-quando', permanent: true },
      { source: '/blog/o-que-e-avcb-e-quando-ele-e-obrigatorio', destination: '/blog/quem-precisa-de-avcb', permanent: true },
      { source: '/blog/avcb-restaurante-sao-paulo', destination: '/blog/avcb-para-restaurante-em-sp-como-regularizar-em-2026', permanent: true },
      // === CONSOLIDACAO SEO - paginas de bairro (Fase 1) - gerado 20/05/2026 ===
      { source: '/avcb-alphaville-barueri', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-analia-franco', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-aricanduva', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-barueri-alphaville', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-bela-vista', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-bom-retiro', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-brooklin', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-butanta', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-campinas-barao-geraldo', destination: '/avcb-campinas', permanent: true },
      { source: '/avcb-campinas-cambui', destination: '/avcb-campinas', permanent: true },
      { source: '/avcb-campinas-castelo', destination: '/avcb-campinas', permanent: true },
      { source: '/avcb-campinas-centro', destination: '/avcb-campinas', permanent: true },
      { source: '/avcb-campinas-guanabara', destination: '/avcb-campinas', permanent: true },
      { source: '/avcb-campinas-mansoes-santo-antonio', destination: '/avcb-campinas', permanent: true },
      { source: '/avcb-campinas-taquaral', destination: '/avcb-campinas', permanent: true },
      { source: '/avcb-campo-belo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-campo-grande', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-carrao', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-casa-verde', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-centro-bela-vista', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-centro-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-consolacao', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-freguesia-do-o', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-guarulhos-aeroporto', destination: '/avcb-guarulhos', permanent: true },
      { source: '/avcb-guarulhos-bonsucesso', destination: '/avcb-guarulhos', permanent: true },
      { source: '/avcb-guarulhos-centro', destination: '/avcb-guarulhos', permanent: true },
      { source: '/avcb-guarulhos-macedo', destination: '/avcb-guarulhos', permanent: true },
      { source: '/avcb-guarulhos-maia', destination: '/avcb-guarulhos', permanent: true },
      { source: '/avcb-guarulhos-pimentas', destination: '/avcb-guarulhos', permanent: true },
      { source: '/avcb-guarulhos-vila-augusta', destination: '/avcb-guarulhos', permanent: true },
      { source: '/avcb-higienopolis', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-ipiranga', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-itaim-bibi', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-itaquera', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-jabaquara', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-jacana', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-jardins', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-lapa', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-liberdade', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-limao', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-moema', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-mooca', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-morumbi', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-penha', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-perdizes', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-pinheiros', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-pompeia', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-republica', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-sacoma', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-santa-cecilia', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-santana', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-santo-amaro', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-santos-aparecida', destination: '/avcb-santos', permanent: true },
      { source: '/avcb-santos-boqueirao', destination: '/avcb-santos', permanent: true },
      { source: '/avcb-santos-centro', destination: '/avcb-santos', permanent: true },
      { source: '/avcb-santos-embare', destination: '/avcb-santos', permanent: true },
      { source: '/avcb-santos-gonzaga', destination: '/avcb-santos', permanent: true },
      { source: '/avcb-santos-ponta-da-praia', destination: '/avcb-santos', permanent: true },
      { source: '/avcb-sapopemba', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-saude', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-se', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-tatuape', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-tucuruvi', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-vila-clementino', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-vila-leopoldina', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-vila-madalena', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-vila-mariana', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-vila-olimpia', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-vila-prudente', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-vila-re', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-analia-franco', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-aricanduva', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-carrao', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-casa-verde', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-condominio-agua-branca', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-altos-de-santana', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-analia-franco', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-bela-vista', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-brooklin', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-campo-belo', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-chacara-klabin', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-chacara-santo-antonio', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-cidade-moncoes', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-consolacao', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-higienopolis', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-ipiranga', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-itaim-bibi', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-jabaquara', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-jardins', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-lapa', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-moema', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-moema-indios', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-moema-passaros', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-mooca', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-morumbi', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-perdizes', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-pinheiros', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-santana', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-santo-amaro', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-saude', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-tatuape', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-tucuruvi', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-vila-andrade', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-vila-clementino', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-vila-ipojuca', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-vila-leopoldina', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-vila-mariana', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-vila-nova-conceicao', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-vila-olimpia', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-condominio-vila-prudente', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-consolacao', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-freguesia-do-o', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-higienopolis', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-ipiranga', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-itaquera', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-jabaquara', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-jacana', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-liberdade', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-limao', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-morumbi', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-paraiso', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-penha', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-santana', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-sapopemba', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-saude', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-se', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-tucuruvi', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-vila-leopoldina', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-vila-madalena', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-vila-prudente', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-avcb-vila-re', destination: '/renovacao-avcb', permanent: true },
      { source: '/renovacao-clcb-aclimacao-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-agua-rasa-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-aricanduva-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-bela-vista-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-belem-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-bras-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-brasilandia-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-brooklin-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-butanta-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-cambuci-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-campo-belo-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-campo-limpo-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-cangaiba-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-capao-redondo-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-carrao-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-casa-verde-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-consolacao-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-cursino-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-freguesia-do-o-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-graja-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-higienopolis-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-interlagos-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-ipiranga-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-itaim-bibi-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-itaquera-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-jabaquara-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-jacana-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-jardins-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-lapa-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-liberdade-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-mandaqui-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-mboi-mirim-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-moema-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-mooca-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-morumbi-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-paraiso-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-penha-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-perdizes-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-pinheiros-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-pirituba-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-pompeia-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-rio-pequeno-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-sacoma-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-santana-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-santo-amaro-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-sao-mateus-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-sao-miguel-paulista-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-sapopemba-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-saude-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-tatuape-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-tremembe-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-tucuruvi-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-vila-andrade-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-vila-formosa-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-vila-madalena-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-vila-mariana-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-vila-olimpia-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-vila-prudente-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      // === CONSOLIDACAO SEO - ocupacao duplicada (Fase 1b) ===
      { source: '/alvara-bombeiro-academia-sao-paulo', destination: '/renovacao-avcb-academia-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-casa-de-repouso-sao-paulo', destination: '/renovacao-avcb-casa-de-repouso-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-casa-noturna-boate-sao-paulo', destination: '/renovacao-avcb-casa-noturna-boate-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-condominio-sao-paulo', destination: '/avcb-para-condominio-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-consultorio-medico-sao-paulo', destination: '/renovacao-avcb-consultorio-medico-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-creche-sao-paulo', destination: '/renovacao-avcb-creche-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-escritorio-sao-paulo', destination: '/avcb-comercial-escritorio-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-farmacia-drogaria-sao-paulo', destination: '/avcb-farmacia-drogaria-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-galpao-industrial-sao-paulo', destination: '/avcb-galpao-industrial-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-hospital-clinica-sao-paulo', destination: '/avcb-hospital-clinica-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-hostel-sao-paulo', destination: '/avcb-hostel-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-igreja-sao-paulo', destination: '/renovacao-avcb-igreja-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-motel-sao-paulo', destination: '/avcb-motel-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-padaria-sao-paulo', destination: '/renovacao-avcb-padaria-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-posto-combustivel-sao-paulo', destination: '/avcb-posto-combustivel-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-salao-de-festas-sao-paulo', destination: '/avcb-salao-de-festas-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-shopping-sao-paulo', destination: '/renovacao-avcb-shopping-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-supermercado-sao-paulo', destination: '/avcb-supermercado-sao-paulo', permanent: true },
      { source: '/avcb-para-academia-sao-paulo', destination: '/renovacao-avcb-academia-sao-paulo', permanent: true },
      { source: '/avcb-para-casa-de-repouso-sao-paulo', destination: '/renovacao-avcb-casa-de-repouso-sao-paulo', permanent: true },
      { source: '/avcb-para-creche-sao-paulo', destination: '/renovacao-avcb-creche-sao-paulo', permanent: true },
      { source: '/avcb-para-escritorio-sao-paulo', destination: '/avcb-comercial-escritorio-sao-paulo', permanent: true },
      { source: '/avcb-para-evento-corporativo', destination: '/ptotep', permanent: true },
      { source: '/avcb-para-evento-em-shopping', destination: '/ptotep', permanent: true },
      { source: '/avcb-para-exposicao', destination: '/ptotep', permanent: true },
      { source: '/avcb-para-feira', destination: '/ptotep', permanent: true },
      { source: '/avcb-para-igreja-sao-paulo', destination: '/renovacao-avcb-igreja-sao-paulo', permanent: true },
      { source: '/avcb-para-padaria-sao-paulo', destination: '/renovacao-avcb-padaria-sao-paulo', permanent: true },
      { source: '/avcb-para-renovacao-de-seguro', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-para-shopping-sao-paulo', destination: '/renovacao-avcb-shopping-sao-paulo', permanent: true },
      { source: '/avcb-para-show', destination: '/ptotep', permanent: true },
      { source: '/avcb-paraiso', destination: '/avcb-sao-paulo', permanent: true },
      // === CONSOLIDACAO SEO - servico x ocupacao (Fase 1c) ===
      { source: '/alarme-de-incendio-comercial-escritorio-sp', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/alarme-de-incendio-escola-faculdade-sp', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/alarme-de-incendio-galpao-industrial-sp', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/alarme-de-incendio-hospital-clinica-sp', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/alarme-de-incendio-para-condominio-sao-paulo', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/alarme-incendio-centro-distribuicao-sp', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/alarme-incendio-obrigatorio-avcb-sp', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/alarme-incendio-supermercado-avcb-sp', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/brigada-incendio-centro-distribuicao-sp', destination: '/treinamento-brigada', permanent: true },
      { source: '/brigada-incendio-galpao-industrial-sp', destination: '/treinamento-brigada', permanent: true },
      { source: '/brigada-incendio-hospital-sp', destination: '/treinamento-brigada', permanent: true },
      { source: '/brigada-incendio-hotel-sp', destination: '/treinamento-brigada', permanent: true },
      { source: '/brigada-incendio-obrigatoria-avcb-sp', destination: '/treinamento-brigada', permanent: true },
      { source: '/brigada-incendio-predio-comercial-sp', destination: '/treinamento-brigada', permanent: true },
      { source: '/brigada-incendio-shopping-sp', destination: '/treinamento-brigada', permanent: true },
      { source: '/brigada-incendio-supermercado-sp', destination: '/treinamento-brigada', permanent: true },
      { source: '/escada-pressurizada-condominio-sp', destination: '/escada-pressurizada-sao-paulo', permanent: true },
      { source: '/escada-pressurizada-edificio-comercial-sp', destination: '/escada-pressurizada-sao-paulo', permanent: true },
      { source: '/escada-pressurizada-galpao-industrial-sp', destination: '/escada-pressurizada-sao-paulo', permanent: true },
      { source: '/escada-pressurizada-hospital-sp', destination: '/escada-pressurizada-sao-paulo', permanent: true },
      { source: '/escada-pressurizada-hotel-sp', destination: '/escada-pressurizada-sao-paulo', permanent: true },
      { source: '/escada-pressurizada-obrigatoria-avcb-sp', destination: '/escada-pressurizada-sao-paulo', permanent: true },
      { source: '/escada-pressurizada-shopping-sp', destination: '/escada-pressurizada-sao-paulo', permanent: true },
      { source: '/hidrante-centro-distribuicao-sp', destination: '/hidrantes', permanent: true },
      { source: '/hidrante-obrigatorio-avcb-sp', destination: '/hidrantes', permanent: true },
      { source: '/hidrante-supermercado-avcb-sp', destination: '/hidrantes', permanent: true },
      { source: '/projeto-combate-incendio-corpo-bombeiros-sp', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-escada-pressurizada-avcb-sao-paulo', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-incendio-centro-distribuicao-sp', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-incendio-edificio-comercial-sp', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-incendio-galpao-industrial-avcb-sp', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-incendio-hospital-sp', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-incendio-hotel-sp', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-incendio-industria-quimica-sp', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-incendio-obrigatorio-sp', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-incendio-para-avcb-sp', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-incendio-shopping-center-sp', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-incendio-supermercado-sp', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-spda-para-raios-sao-paulo', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-vga-sistema-sprinkler-sp', destination: '/projetos-incendio', permanent: true },
      { source: '/sistema-alarme-incendio-hotel-avcb-sp', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-alarme-incendio-industria-quimica-sp', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-alarme-incendio-shopping-center-sp', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-de-hidrantes-para-academia-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/sistema-de-hidrantes-para-condominio-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/sistema-de-hidrantes-para-escola-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/sistema-de-hidrantes-para-galpao-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/sistema-de-hidrantes-para-hospital-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/sistema-de-hidrantes-para-hotel-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/sistema-de-hidrantes-para-industria-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/sistema-de-hidrantes-para-pousada-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/sistema-de-hidrantes-para-restaurante-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/sistema-de-sprinkler-para-academia-sao-paulo', destination: '/sprinklers', permanent: true },
      { source: '/sistema-de-sprinkler-para-condominio-sao-paulo', destination: '/sprinklers', permanent: true },
      { source: '/sistema-de-sprinkler-para-escola-sao-paulo', destination: '/sprinklers', permanent: true },
      { source: '/sistema-de-sprinkler-para-hospital-sao-paulo', destination: '/sprinklers', permanent: true },
      { source: '/sistema-de-sprinkler-para-hotel-sao-paulo', destination: '/sprinklers', permanent: true },
      { source: '/sistema-de-sprinkler-para-industria-sao-paulo', destination: '/sprinklers', permanent: true },
      { source: '/sistema-de-sprinkler-para-pousada-sao-paulo', destination: '/sprinklers', permanent: true },
      { source: '/sistema-de-sprinkler-para-restaurante-sao-paulo', destination: '/sprinklers', permanent: true },
      { source: '/sistema-hidrante-edificio-comercial-sp', destination: '/hidrantes', permanent: true },
      { source: '/sistema-hidrante-hospital-avcb-sp', destination: '/hidrantes', permanent: true },
      { source: '/sistema-hidrante-hotel-avcb-sp', destination: '/hidrantes', permanent: true },
      { source: '/sistema-hidrante-shopping-center-sp', destination: '/hidrantes', permanent: true },
      { source: '/sistema-sprinkler-edificio-comercial-sp', destination: '/sprinklers', permanent: true },
      { source: '/sistema-sprinkler-galpao-industrial-avcb-sp', destination: '/sprinklers', permanent: true },
      { source: '/sistema-sprinkler-hospital-avcb-sp', destination: '/sprinklers', permanent: true },
      { source: '/sistema-sprinkler-hotel-avcb-sp', destination: '/sprinklers', permanent: true },
      { source: '/sistema-sprinkler-shopping-center-sp', destination: '/sprinklers', permanent: true },
      { source: '/spda-para-raios-sao-paulo', destination: '/spda', permanent: true },
      { source: '/sprinkler-centro-distribuicao-sp', destination: '/sprinklers', permanent: true },
      { source: '/sprinkler-obrigatorio-avcb-sp', destination: '/sprinklers', permanent: true },
      { source: '/sprinkler-supermercado-avcb-sp', destination: '/sprinklers', permanent: true },
      { source: '/treinamento-brigada-incendio-sp', destination: '/treinamento-brigada', permanent: true },
      { source: '/valvula-alarme-incendio-sp', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/valvula-retencao-sprinkler-sp', destination: '/vga-sprinkler-sao-paulo', permanent: true },
      { source: '/vga-centro-distribuicao-sp', destination: '/vga-sprinkler-sao-paulo', permanent: true },
      { source: '/vga-galpao-industrial-sp', destination: '/vga-sprinkler-sao-paulo', permanent: true },
      { source: '/vga-hospital-sp', destination: '/vga-sprinkler-sao-paulo', permanent: true },
      { source: '/vga-hotel-sp', destination: '/vga-sprinkler-sao-paulo', permanent: true },
      { source: '/vga-shopping-center-sp', destination: '/vga-sprinkler-sao-paulo', permanent: true },
      { source: '/vga-supermercado-sp', destination: '/vga-sprinkler-sao-paulo', permanent: true },
      // === CONSOLIDACAO SEO - laudos (Fase 1d) ===
      { source: '/laudo-alarme-incendio-condominio-sao-paulo', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/laudo-alarme-incendio-escola-sao-paulo', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/laudo-alarme-incendio-hotel-sao-paulo', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/laudo-alarme-incendio-restaurante-sao-paulo', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/laudo-alarme-incendio-sao-paulo', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-academia-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-bar-restaurante-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-casa-de-repouso-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-casa-noturna-boate-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-condominio-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-consultorio-medico-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-creche-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-escola-faculdade-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-escritorio-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-farmacia-drogaria-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-galpao-industrial-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-hospital-clinica-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-hostel-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-hotel-pousada-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-igreja-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-motel-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-padaria-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-posto-combustivel-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-salao-de-festas-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-shopping-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-supermercado-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-escada-pressurizada-sp', destination: '/escada-pressurizada-sao-paulo', permanent: true },
      { source: '/laudo-hidrante-condominio-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/laudo-hidrante-escola-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/laudo-hidrante-galpao-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/laudo-hidrante-restaurante-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/laudo-sistema-hidrantes-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/laudo-spda-para-raios-sao-paulo', destination: '/spda', permanent: true },
      { source: '/laudo-sprinkler-clinica-sao-paulo', destination: '/sprinklers', permanent: true },
      { source: '/laudo-sprinkler-condominio-sao-paulo', destination: '/sprinklers', permanent: true },
      { source: '/laudo-sprinkler-galpao-sao-paulo', destination: '/sprinklers', permanent: true },
      { source: '/laudo-sprinkler-hotel-sao-paulo', destination: '/sprinklers', permanent: true },
      { source: '/laudo-sprinkler-sao-paulo', destination: '/sprinklers', permanent: true },
      // === CONSOLIDACAO SEO - porta corta-fogo (Fase 1e) ===
      { source: '/adequacao-porta-corta-fogo-avcb-sp', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
      { source: '/empresa-manutencao-porta-corta-fogo-sp', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
      { source: '/manutencao-porta-corta-fogo-abc-paulista', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
      { source: '/manutencao-porta-corta-fogo-campinas', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
      { source: '/manutencao-porta-corta-fogo-guarulhos', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
      { source: '/manutencao-porta-corta-fogo-santo-amaro-sp', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
      { source: '/manutencao-porta-corta-fogo-zona-sul-sp', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
      { source: '/orcamento-porta-corta-fogo-sp', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
      { source: '/porta-corta-fogo-condenada-sp', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
      { source: '/porta-corta-fogo-condominio-sp', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
      { source: '/porta-corta-fogo-galpao-industrial-sp', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
      { source: '/porta-corta-fogo-hospital-sp', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
      { source: '/porta-corta-fogo-hotel-sp', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
      { source: '/porta-corta-fogo-nao-fecha-sp', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
      { source: '/troca-mola-hidraulica-porta-corta-fogo-sp', destination: '/manutencao-porta-corta-fogo-sp', permanent: true },
    ];
  },
};

export default nextConfig;
