/** @type {import('next').NextConfig} */
const nextConfig = {
  compress: true,
  poweredByHeader: false,
  images: {
    formats: ['image/avif', 'image/webp'],
    minimumCacheTTL: 31536000,
    dangerouslyAllowSVG: true,
    contentDispositionType: 'attachment',
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
  async headers() {
    // Headers de seguranca aplicados a todas as rotas — protegem contra XSS,
    // clickjacking, sniffing e fortalecem a postura de seguranca do site.
    const securityHeaders = [
      // Forca HTTPS (HSTS) — 2 anos + subdomains. Inclui preload para a HSTS list do Chrome.
      { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
      // Bloqueia o site em iframes externos — previne clickjacking
      { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
      // Impede browsers de adivinhar MIME type — previne ataques de MIME sniffing
      { key: 'X-Content-Type-Options', value: 'nosniff' },
      // Controla qual referrer enviamos (privacidade do usuario)
      { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
      // Bloqueia features sensiveis que nao usamos
      { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=(), interest-cohort=()' },
      // CSP — permite GA4, GTM, WhatsApp, fontes Google, imagens externas usadas
      {
        key: 'Content-Security-Policy',
        value: [
          "default-src 'self'",
          "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://*.googletagmanager.com https://www.google-analytics.com https://*.google-analytics.com",
          "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
          "font-src 'self' data: https://fonts.gstatic.com",
          "img-src 'self' data: https: blob:",
          "connect-src 'self' https://www.google-analytics.com https://*.google-analytics.com https://www.googletagmanager.com https://formsubmit.co",
          "frame-src 'self' https://www.youtube.com https://www.youtube-nocookie.com",
          "frame-ancestors 'self'",
          "base-uri 'self'",
          "form-action 'self' https://formsubmit.co",
          "object-src 'none'",
          "upgrade-insecure-requests",
        ].join('; '),
      },
    ];

    return [
      {
        source: '/images/:path*',
        headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
      },
      {
        source: '/_next/static/:path*',
        headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
      },
      // Aplica headers de seguranca em TODAS as rotas (HTML, API, etc)
      {
        source: '/:path*',
        headers: securityHeaders,
      },
    ];
  },
  async redirects() {
    return [
      { source: '/avcb-sao-paulo-AVCB', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/treinamento-brigada-Brigada', destination: '/treinamento-brigada', permanent: true },
      { source: '/hidrantes-Hidrantes', destination: '/hidrantes', permanent: true },
      { source: '/sprinklers-Sprinklers', destination: '/sprinklers', permanent: true },
      { source: '/avcb-com%C3%A9rcio', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/manutencao-Manuten%C3%A7%C3%A3o', destination: '/manutencao', permanent: true },
      { source: '/renovacao-avcb-moema', destination: '/renovacao-avcb-condominio-moema', permanent: true },
      { source: '/renovacao-avcb-vila-olimpia', destination: '/renovacao-avcb-condominio-vila-olimpia', permanent: true },
      { source: '/renovacao-avcb-pinheiros', destination: '/renovacao-avcb-condominio-pinheiros', permanent: true },
      { source: '/renovacao-avcb-perdizes', destination: '/renovacao-avcb-condominio-perdizes', permanent: true },
      { source: '/renovacao-avcb-bela-vista', destination: '/renovacao-avcb-condominio-bela-vista', permanent: true },
      { source: '/renovacao-avcb-galpao-industrial-tatuape', destination: '/avcb-tatuape', permanent: true },
      { source: '/avcb-zona-leste', destination: '/avcb-zona-leste-sao-paulo', permanent: true },
      { source: '/avcb-zona-oeste', destination: '/avcb-zona-oeste-sao-paulo', permanent: true },
      { source: '/avcb-zona-norte', destination: '/avcb-zona-norte-sao-paulo', permanent: true },
      { source: '/avcb-comercio', destination: '/avcb-para-escritorio-sao-paulo', permanent: true },
      { source: '/quanto-custa-avcb-em-sao-paulo', destination: '/quanto-custa-avcb-sao-paulo', permanent: true },
      {
        source: '/avcb-restaurante',
        destination: '/avcb-restaurante-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-restaurantes',
        destination: '/avcb-restaurante-sao-paulo',
        permanent: true,
      },
      {
        source: '/projeto-tecnico-ocupacao-temporaria-edificacao-permanente',
        destination: '/ptotep',
        permanent: true,
      },
      {
        source: '/projeto-tecnico-para-evento',
        destination: '/ptotep',
        permanent: true,
      },
      {
        source: '/avcb-para-evento',
        destination: '/ptotep',
        permanent: true,
      },
      {
        source: '/avcb-bares-restaurantes-sao-paulo',
        destination: '/avcb-restaurante-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-bar-sao-paulo',
        destination: '/avcb-restaurante-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-bar-sao-paulo',
        destination: '/avcb-restaurante-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb',
        destination: '/avcb-sao-paulo',
        permanent: true,
      },
      {
        source: '/mapa-páginas',
        destination: '/mapa-paginas',
        permanent: true,
      },
      {
        source: '/mapa-p%C3%A1ginas',
        destination: '/mapa-paginas',
        permanent: true,
      },
      {
        source: '/avcb-para-farmacia-sao-paulo',
        destination: '/avcb-farmacia-drogaria-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-drogaria-sao-paulo',
        destination: '/avcb-farmacia-drogaria-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-boate-sao-paulo',
        destination: '/avcb-casas-noturnas-boates-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-casa-noturna-sao-paulo',
        destination: '/avcb-casas-noturnas-boates-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-bar-com-show-sao-paulo',
        destination: '/avcb-casas-noturnas-boates-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-clinica-odontologica-sao-paulo',
        destination: '/avcb-consultorios-medicos-odontologicos-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-clinica-veterinaria-sao-paulo',
        destination: '/avcb-clinica-hospital-veterinario-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-clinica-veterinaria-sao-paulo',
        destination: '/avcb-clinica-hospital-veterinario-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-hospital-veterinario-sao-paulo',
        destination: '/avcb-clinica-hospital-veterinario-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-hospital-veterinaria-sao-paulo',
        destination: '/avcb-clinica-hospital-veterinario-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-pet-shop-sao-paulo',
        destination: '/avcb-clinica-hospital-veterinario-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-estacionamento-sao-paulo',
        destination: '/avcb-estacionamento-garagem-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-estacionamento-sao-paulo',
        destination: '/avcb-estacionamento-garagem-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-garagem-sao-paulo',
        destination: '/avcb-estacionamento-garagem-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-garagem-sao-paulo',
        destination: '/avcb-estacionamento-garagem-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-estacionamento-rotativo-sao-paulo',
        destination: '/avcb-estacionamento-garagem-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-bar-adega-sao-paulo',
        destination: '/avcb-restaurante-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-salao-de-festas-sao-paulo',
        destination: '/avcb-salao-de-festas-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-hotel-sao-paulo',
        destination: '/avcb-hoteis-pousadas-sao-paulo',
        permanent: true,
      },
      {
        source: '/avcb-para-pousada-sao-paulo',
        destination: '/avcb-hoteis-pousadas-sao-paulo',
        permanent: true,
      },
      // Serviços legados → páginas dedicadas
      { source: '/servicos/chuveiro-automatico-sprinkler-sao-paulo', destination: '/sprinklers', permanent: true },
      { source: '/servicos/instalacao-hidrante-sao-paulo', destination: '/hidrantes', permanent: true },
      { source: '/servicos/spda-para-raios-sao-paulo', destination: '/spda', permanent: true },
      { source: '/servicos/manutencao-sistemas-incendio', destination: '/manutencao', permanent: true },
      { source: '/servicos/projetos-seguranca-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/servicos/clcb-sao-paulo', destination: '/clcb-sao-paulo', permanent: true },
      { source: '/servicos/avcb-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/servicos/avcb-bares-restaurantes-sao-paulo', destination: '/avcb-restaurante-sao-paulo', permanent: true },
      { source: '/servicos/avcb-pousada-sao-paulo', destination: '/avcb-hoteis-pousadas-sao-paulo', permanent: true },
      { source: '/servicos/avcb-hoteis-pousadas-sao-paulo', destination: '/avcb-hoteis-pousadas-sao-paulo', permanent: true },
      { source: '/servicos/avcb-escola-faculdade-sao-paulo', destination: '/avcb-para-escola-sao-paulo', permanent: true },
      { source: '/servicos/avcb-para-drogaria-sao-paulo', destination: '/avcb-farmacia-drogaria-sao-paulo', permanent: true },
      { source: '/servicos/avcb-para-casa-noturna-sao-paulo', destination: '/avcb-casas-noturnas-boates-sao-paulo', permanent: true },
      { source: '/servicos/avcb-para-bar-com-show-sao-paulo', destination: '/avcb-casas-noturnas-boates-sao-paulo', permanent: true },
      // Brigada e preço
      { source: '/brigada', destination: '/treinamento-brigada', permanent: true },
      { source: '/avcb-preco', destination: '/quanto-custa-avcb-sao-paulo', permanent: true },
      // Edifício residencial → condomínio (mesma intenção, página customizada mais rica existe)
      // Doorway pairs — consolidação de intenção duplicada
      { source: '/sistema-hidrante-galpao-industrial-avcb-sp', destination: '/sistema-de-hidrantes-para-galpao-sao-paulo', permanent: true },
      { source: '/sistema-alarme-incendio-galpao-industrial-avcb-sp', destination: '/alarme-de-incendio-galpao-industrial-sp', permanent: true },
      { source: '/sistema-alarme-incendio-hospital-avcb-sp', destination: '/alarme-de-incendio-hospital-clinica-sp', permanent: true },
      { source: '/sistema-alarme-incendio-edificio-comercial-sp', destination: '/alarme-de-incendio-comercial-escritorio-sp', permanent: true },
      { source: '/projeto-escada-pressurizada-avcb', destination: '/projeto-escada-pressurizada-avcb-sao-paulo', permanent: true },
      { source: '/sistema-hidrante-industria-quimica-sp', destination: '/sistema-de-hidrantes-para-industria-sao-paulo', permanent: true },
      { source: '/sistema-sprinkler-industria-quimica-sp', destination: '/sistema-de-sprinkler-para-industria-sao-paulo', permanent: true },
      // Páginas canibalizantes — consolidação de autoridade
      { source: '/avcb-condominio-sao-paulo', destination: '/avcb-para-condominio-sao-paulo', permanent: true },
      // Blog — consolidação de posts canibalizando (mesma intenção de busca)
      { source: '/blog/quanto-tempo-demora-para-emitir-o-avcb-sp', destination: '/blog/prazo-para-emissao-de-avcb', permanent: true },
      { source: '/blog/avcb-vencido-o-que-fazer-evitar-interdicao', destination: '/avcb-vencido-o-que-fazer', permanent: true },
      { source: '/blog/quanto-custa-avcb-sp-precos-prazos', destination: '/blog/quanto-custa-avcb-em-sao-paulo', permanent: true },
      { source: '/blog/diferenca-entre-avcb-e-clcb-em-sao-paulo', destination: '/blog/diferenca-entre-avcb-e-clcb', permanent: true },
      { source: '/blog/avcb-x-clcb-diferenca-na-pratica', destination: '/blog/diferenca-entre-avcb-e-clcb', permanent: true },
      { source: '/blog/sprinkler-obrigatorio-sp', destination: '/blog/sprinkler-obrigatorio-para-quem-e-quando', permanent: true },
      { source: '/blog/o-que-e-avcb-e-quando-ele-e-obrigatorio', destination: '/blog/quem-precisa-de-avcb', permanent: true },
      { source: '/blog/avcb-restaurante-sao-paulo', destination: '/blog/avcb-para-restaurante-em-sp-como-regularizar-em-2026', permanent: true },
      // Posts canibalizando páginas de serviço — consolidação de autoridade
      { source: '/blog/como-regularizar-condominio-corpo-de-bombeiros', destination: '/avcb-para-condominio-sao-paulo', permanent: true },
      { source: '/blog/diferenca-entre-avcb-e-ptotep-eventos', destination: '/diferenca-avcb-ptotep', permanent: true },
      { source: '/blog/alarme-incendio-galpao-industrial-obrigatorio-sp', destination: '/alarme-de-incendio-galpao-industrial-sp', permanent: true },
      // URLs antigas renomeadas — redirect para a página do MESMO bairro (restauração jul/2026)
      { source: '/avcb-barueri-alphaville', destination: '/avcb-alphaville-barueri', permanent: true },
      // ===== 08/08/2026 — 404 reais do GSC: rota para a pagina irma existente =====
      { source: '/alarmes', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/avcb-entretenimento', destination: '/avcb-casas-noturnas-boates-sao-paulo', permanent: true },
      { source: '/avcb-para-restaurante-sao-paulo', destination: '/avcb-restaurante-sao-paulo', permanent: true },
      { source: '/avcb-para-supermercado-sao-paulo', destination: '/avcb-supermercado-sao-paulo', permanent: true },
      { source: '/avcb-vila-guilherme', destination: '/avcb-zona-norte-sao-paulo', permanent: true },
      { source: '/comunique-se-corpo-de-bombeiros-sao-paulo', destination: '/blog/o-que-e-comunique-se-corpo-de-bombeiros', permanent: true },
      { source: '/renovacao-avcb-condominio-aricanduva', destination: '/renovacao-avcb-aricanduva', permanent: true },
      { source: '/renovacao-avcb-condominio-barra-funda', destination: '/renovacao-avcb-barra-funda', permanent: true },
      { source: '/renovacao-avcb-condominio-carrao', destination: '/renovacao-avcb-carrao', permanent: true },
      { source: '/renovacao-avcb-condominio-casa-verde', destination: '/renovacao-avcb-casa-verde', permanent: true },
      { source: '/renovacao-avcb-condominio-freguesia-do-o', destination: '/renovacao-avcb-freguesia-do-o', permanent: true },
      { source: '/renovacao-avcb-condominio-itaquera', destination: '/renovacao-avcb-itaquera', permanent: true },
      { source: '/renovacao-avcb-condominio-jacana', destination: '/renovacao-avcb-jacana', permanent: true },
      { source: '/renovacao-avcb-condominio-liberdade', destination: '/renovacao-avcb-liberdade', permanent: true },
      { source: '/renovacao-avcb-condominio-limao', destination: '/renovacao-avcb-limao', permanent: true },
      { source: '/renovacao-avcb-condominio-paraiso', destination: '/renovacao-avcb-paraiso', permanent: true },
      { source: '/renovacao-avcb-condominio-penha', destination: '/renovacao-avcb-penha', permanent: true },
      { source: '/renovacao-avcb-condominio-sapopemba', destination: '/renovacao-avcb-sapopemba', permanent: true },
      { source: '/renovacao-avcb-condominio-se', destination: '/renovacao-avcb-se', permanent: true },
      { source: '/renovacao-avcb-condominio-vila-madalena', destination: '/renovacao-avcb-vila-madalena', permanent: true },
      { source: '/renovacao-avcb-condominio-vila-re', destination: '/renovacao-avcb-vila-re', permanent: true },
      { source: '/renovacao-clcb-ermelino-matarazzo-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-jardim-angela-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-vila-matilde-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/renovacao-clcb-zona-centro-sao-paulo', destination: '/renovacao-clcb-sao-paulo', permanent: true },
      { source: '/sistema-de-sprinkler-para-galpao-sao-paulo', destination: '/sistema-sprinkler-galpao-industrial-avcb-sp', permanent: true },
      { source: '/sprinkler-galpao-avcb-sp', destination: '/sistema-sprinkler-galpao-industrial-avcb-sp', permanent: true },
      { source: '/sprinkler-hospital-avcb-sp', destination: '/sistema-sprinkler-hospital-avcb-sp', permanent: true },
      { source: '/sprinkler-hotel-avcb-sp', destination: '/sistema-sprinkler-hotel-avcb-sp', permanent: true },
      { source: '/sprinkler-shopping-center-avcb-sp', destination: '/sistema-sprinkler-shopping-center-sp', permanent: true },
      // ===== 30/09/2026 — URLs do site antigo que davam 404 no Search Console (mapa por assunto) =====
      { source: '/alvara-bombeiro-sao-paulo', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/alvara-funcionamento', destination: 'https://drd1.com.br/alvara-de-funcionamento-sao-paulo', permanent: true },
      { source: '/alvara-funcionamento-empresas', destination: 'https://drd1.com.br/alvara-de-funcionamento-sao-paulo', permanent: true },
      { source: '/alvara-funcionamento-industrias', destination: 'https://drd1.com.br/alvara-de-funcionamento-sao-paulo', permanent: true },
      { source: '/alvara-funcionamento-posto-gasolina', destination: 'https://drd1.com.br/alvara-de-funcionamento-sao-paulo', permanent: true },
      { source: '/art-no-envidracamento-sacadas', destination: 'https://drd1.com.br/laudo-de-envidracamento-de-sacada-sao-paulo', permanent: true },
      { source: '/assessoria-alf', destination: 'https://drd1.com.br/auto-de-licenca-de-funcionamento-sao-paulo', permanent: true },
      { source: '/assessoria-alvara-funcionamento', destination: 'https://drd1.com.br/alvara-de-funcionamento-sao-paulo', permanent: true },
      { source: '/assessoria-auto-licenca-funcionamento', destination: 'https://drd1.com.br/auto-de-licenca-de-funcionamento-sao-paulo', permanent: true },
      { source: '/assessoria-avcb', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/assessoria-empresarial-alvara-funcionamento', destination: 'https://drd1.com.br/alvara-de-funcionamento-sao-paulo', permanent: true },
      { source: '/assessoria-licencas-alvaras-funcionamento', destination: 'https://drd1.com.br/alvara-de-funcionamento-sao-paulo', permanent: true },
      { source: '/avcb-auto-vistoria-do-corpo-bombeiros', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-como-funciona', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-corpo-bombeiros', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-da-empresa', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-do-predio', destination: '/avcb-para-condominio-sao-paulo', permanent: true },
      { source: '/avcb-exemplos', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-incendio', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/avcb-orcamento', destination: '/quanto-custa-avcb-sao-paulo', permanent: true },
      { source: '/avcb-para-shopping-sao-pago', destination: '/avcb-para-shopping-sao-paulo', permanent: true },
      { source: '/avcb-para-shopping-sao-pulo', destination: '/avcb-para-shopping-sao-paulo', permanent: true },
      { source: '/avcb-posto-combustivel-sao-pulo', destination: '/avcb-posto-combustivel-sao-paulo', permanent: true },
      { source: '/avcb-predio-comercial', destination: '/avcb-para-escritorio-sao-paulo', permanent: true },
      { source: '/avcb-predio-residencial', destination: '/avcb-para-condominio-sao-paulo', permanent: true },
      { source: '/avcb-projeto', destination: '/projeto-incendio-para-avcb-sp', permanent: true },
      { source: '/avcb-quanto-custa', destination: '/quanto-custa-avcb-sao-paulo', permanent: true },
      { source: '/avcb-salao-de-sao-paulo', destination: '/avcb-salao-de-festas-sao-paulo', permanent: true },
      { source: '/avcb-shopping-sao-paulo', destination: '/avcb-para-shopping-sao-paulo', permanent: true },
      { source: '/avcb-valor', destination: '/quanto-custa-avcb-sao-paulo', permanent: true },
      { source: '/blog/como-emissao-clcb-em-sao-paulo-passo-a-passo', destination: '/blog/como-emitir-clcb-em-sao-paulo-passo-a-passo', permanent: true },
      { source: '/blog/como-emitir-clcb-em-sao-paulos-passo-a-passo', destination: '/blog/como-emitir-clcb-em-sao-paulo-passo-a-passo', permanent: true },
      { source: '/blog/como-funciona-vistoria-do-corpo-bombeiros', destination: '/blog/como-funciona-vistoria-do-corpo-de-bombeiros', permanent: true },
      { source: '/blog/sprinker-obrigatorio-para-quem-e-quando', destination: '/sprinkler-obrigatorio-avcb-sp', permanent: true },
      { source: '/blog/sprinkler-obrigatorio-quem-quando-exigido-sp', destination: '/sprinkler-obrigatorio-avcb-sp', permanent: true },
      { source: '/consultoria-alvara-funcionamento', destination: 'https://drd1.com.br/alvara-de-funcionamento-sao-paulo', permanent: true },
      { source: '/consultoria-avcb', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/custo-avcb', destination: '/quanto-custa-avcb-sao-paulo', permanent: true },
      { source: '/drd2.com.br', destination: '/', permanent: true },
      { source: '/emissao-alvara-funcionamento-shopping', destination: 'https://drd1.com.br/alvara-de-funcionamento-sao-paulo', permanent: true },
      { source: '/emissao-avcb', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/emissao-da-art-envidracamento', destination: 'https://drd1.com.br/laudo-de-envidracamento-de-sacada-sao-paulo', permanent: true },
      { source: '/emissao-laudo-envidracamento-sacadas', destination: 'https://drd1.com.br/laudo-de-envidracamento-de-sacada-sao-paulo', permanent: true },
      { source: '/empresa-alvara-funcionamento-eventos', destination: 'https://drd1.com.br/alvara-de-funcionamento-sao-paulo', permanent: true },
      { source: '/empresa-avcb', destination: '/empresa-avcb-sao-paulo', permanent: true },
      { source: '/empresa-especializada-avcb', destination: '/empresa-avcb-sao-paulo', permanent: true },
      { source: '/empresa-instalacao-raio', destination: '/instalacao-spda-para-raios-sao-paulo', permanent: true },
      { source: '/empresa-instalacao-raio-predial', destination: '/instalacao-spda-para-raios-sao-paulo', permanent: true },
      { source: '/empresa-instalacao-spda', destination: '/instalacao-spda-para-raios-sao-paulo', permanent: true },
      { source: '/empresa-laudo-avcb', destination: '/empresa-avcb-sao-paulo', permanent: true },
      { source: '/empresa-laudo-envidracamento-sacada', destination: 'https://drd1.com.br/laudo-de-envidracamento-de-sacada-sao-paulo', permanent: true },
      { source: '/empresa-projeto-spda', destination: '/projeto-spda-para-raios-sao-paulo', permanent: true },
      { source: '/empresa-projeto-spda-estrutural', destination: '/projeto-spda-para-raios-sao-paulo', permanent: true },
      { source: '/empresa-que-emite-laudo-raios', destination: '/laudo-spda-para-raios-sao-paulo', permanent: true },
      { source: '/empresa-que-faz-avcb', destination: '/empresa-avcb-sao-paulo', permanent: true },
      { source: '/empresa-renovacao-avcb', destination: '/renovacao-avcb', permanent: true },
      { source: '/empresa-spda', destination: '/spda', permanent: true },
      { source: '/empresa-treinamento-brigada-incendio', destination: '/treinamento-brigada', permanent: true },
      { source: '/informacoes', destination: '/sobre', permanent: true },
      { source: '/inspecao-spda', destination: '/laudo-spda-para-raios-sao-paulo', permanent: true },
      { source: '/instalacao-do-sistema-rede-hidrantes', destination: '/hidrantes', permanent: true },
      { source: '/instalacao-raio-residencial', destination: '/instalacao-spda-para-raios-sao-paulo', permanent: true },
      { source: '/instalacao-raios', destination: '/instalacao-spda-para-raios-sao-paulo', permanent: true },
      { source: '/instalacao-raios-edificacoes', destination: '/instalacao-spda-para-raios-sao-paulo', permanent: true },
      { source: '/instalacao-raios-prediais', destination: '/instalacao-spda-para-raios-sao-paulo', permanent: true },
      { source: '/instalacao-rede-hidrantes', destination: '/hidrantes', permanent: true },
      { source: '/instalacao-rede-sprinklers', destination: '/sprinklers', permanent: true },
      { source: '/instalacao-sistema-hidrantes', destination: '/hidrantes', permanent: true },
      { source: '/instalacao-sistema-sprinkler', destination: '/sprinklers', permanent: true },
      { source: '/instalacao-spda', destination: '/instalacao-spda-para-raios-sao-paulo', permanent: true },
      { source: '/instalacao-sprinkler', destination: '/sprinklers', permanent: true },
      { source: '/laudo-aterramento-spda', destination: '/laudo-spda-para-raios-sao-paulo', permanent: true },
      { source: '/laudo-avcb', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-avcb-consulta', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-avcb-preco', destination: '/quanto-custa-avcb-sao-paulo', permanent: true },
      { source: '/laudo-avcb-valor', destination: '/quanto-custa-avcb-sao-paulo', permanent: true },
      { source: '/laudo-envidracamento-apartamentos', destination: 'https://drd1.com.br/laudo-de-envidracamento-de-sacada-sao-paulo', permanent: true },
      { source: '/laudo-envidracamento-predios', destination: 'https://drd1.com.br/laudo-de-envidracamento-de-sacada-sao-paulo', permanent: true },
      { source: '/laudo-envidracamento-sacada', destination: 'https://drd1.com.br/laudo-de-envidracamento-de-sacada-sao-paulo', permanent: true },
      { source: '/laudo-envidracamento-sacada-condominios', destination: 'https://drd1.com.br/laudo-de-envidracamento-de-sacada-sao-paulo', permanent: true },
      { source: '/laudo-raios', destination: '/laudo-spda-para-raios-sao-paulo', permanent: true },
      { source: '/laudo-spda', destination: '/laudo-spda-para-raios-sao-paulo', permanent: true },
      { source: '/laudo-tecnico-avcb', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/laudo-tecnico-descarga-atmosferica', destination: '/laudo-spda-para-raios-sao-paulo', permanent: true },
      { source: '/laudo-tecnico-envidracamento-sacada', destination: 'https://drd1.com.br/laudo-de-envidracamento-de-sacada-sao-paulo', permanent: true },
      { source: '/licenca-funcionamento', destination: 'https://drd1.com.br/alvara-de-funcionamento-sao-paulo', permanent: true },
      { source: '/licencas-alvaras-funcionamento', destination: 'https://drd1.com.br/alvara-de-funcionamento-sao-paulo', permanent: true },
      { source: '/manutencao-do-sistema-rede-hidrantes', destination: '/hidrantes', permanent: true },
      { source: '/manutencao-preventiva-hidrantes', destination: '/hidrantes', permanent: true },
      { source: '/manutencao-preventiva-sistema-combate-incendio', destination: '/manutencao', permanent: true },
      { source: '/manutencao-preventiva-sistema-incendio', destination: '/manutencao', permanent: true },
      { source: '/manutencao-preventiva-sprinkler', destination: '/sprinklers', permanent: true },
      { source: '/manutencao-sprinklers', destination: '/sprinklers', permanent: true },
      { source: '/mapa-site', destination: '/servicos', permanent: true },
      { source: '/montagem-spda', destination: '/instalacao-spda-para-raios-sao-paulo', permanent: true },
      { source: '/orcamento-avcb', destination: '/quanto-custa-avcb-sao-paulo', permanent: true },
      { source: '/preco-avcb', destination: '/quanto-custa-avcb-sao-paulo', permanent: true },
      { source: '/preco-projeto-spda', destination: '/quanto-custa-spda-para-raios-sao-paulo', permanent: true },
      { source: '/preco-renovacao-avcb', destination: '/quanto-custa-renovacao-avcb-sao-paulo', permanent: true },
      { source: '/projeto-alarme-incendio', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/projeto-avcb-preco', destination: '/quanto-custa-projeto-incendio-sp', permanent: true },
      { source: '/projeto-combate-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-combate-incendio-escolas', destination: '/projeto-incendio-para-avcb-sp', permanent: true },
      { source: '/projeto-combate-incendio-preco', destination: '/quanto-custa-projeto-incendio-sp', permanent: true },
      { source: '/projeto-combate-incendio-sp', destination: '/projeto-combate-incendio-corpo-bombeiros-sp', permanent: true },
      { source: '/projeto-combate-incendio-valor', destination: '/quanto-custa-projeto-incendio-sp', permanent: true },
      { source: '/projeto-contra-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-deteccao-alarme-incendio', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/projeto-deteccao-incendio', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/projeto-hidrante', destination: '/hidrantes', permanent: true },
      { source: '/projeto-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-incendio-valor', destination: '/quanto-custa-projeto-incendio-sp', permanent: true },
      { source: '/projeto-prevencao-combate-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-protecao-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-protecao-incendio-panico', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-raios', destination: '/projeto-spda-para-raios-sao-paulo', permanent: true },
      { source: '/projeto-rede-sprinklers', destination: '/sprinklers', permanent: true },
      { source: '/projeto-seguranca-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-sistema-combate-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-sistema-deteccao-alarme-incendio', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/projeto-sistema-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/projeto-spda', destination: '/projeto-spda-para-raios-sao-paulo', permanent: true },
      { source: '/projeto-spda-estrutural', destination: '/projeto-spda-para-raios-sao-paulo', permanent: true },
      { source: '/projeto-spda-galpao', destination: '/projeto-spda-para-raios-sao-paulo', permanent: true },
      { source: '/projeto-sprinkler', destination: '/sprinklers', permanent: true },
      { source: '/quanto-custa-renovacao-avcb-sao-palu', destination: '/quanto-custa-renovacao-avcb-sao-paulo', permanent: true },
      { source: '/quanto-custa-spda-para-raios-sao-pulo', destination: '/quanto-custa-spda-para-raios-sao-paulo', permanent: true },
      { source: '/rede-hidrantes', destination: '/hidrantes', permanent: true },
      { source: '/regularizacao-avcb', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-preco', destination: '/quanto-custa-renovacao-avcb-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-restaurante-sao-paloubi', destination: '/renovacao-avcb-restaurante-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-valor', destination: '/quanto-custa-renovacao-avcb-sao-paulo', permanent: true },
      { source: '/renovacao-de-avcb', destination: '/renovacao-avcb', permanent: true },
      { source: '/servico-avcb', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/servico-instalacao-raio', destination: '/instalacao-spda-para-raios-sao-paulo', permanent: true },
      { source: '/servicos/alvara-de-funcionamento', destination: 'https://drd1.com.br/alvara-de-funcionamento-sao-paulo', permanent: true },
      { source: '/servicos/avcb-auto-de-vistoria-do-corpo-de-bombeiros', destination: '/avcb-sao-paulo', permanent: true },
      { source: '/servicos/certificado-de-licenca-do-corpo-de-bombeiros', destination: '/clcb-sao-paulo', permanent: true },
      { source: '/servicos/instalacao-e-manutencao-de-sistema-de-rede-de-hidrante', destination: '/hidrantes', permanent: true },
      { source: '/servicos/instalacao-e-manutencao-de-sistemas-de-alarme-de-incendio', destination: '/manutencao-alarme-de-incendio-sao-paulo', permanent: true },
      { source: '/servicos/laudo-envidracamento-de-sacada', destination: 'https://drd1.com.br/laudo-de-envidracamento-de-sacada-sao-paulo', permanent: true },
      { source: '/servicos/projeto-de-deteccao-e-alarme-de-incendio', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/servicos/projeto-de-prevencao-e-combate-a-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/servicos/projeto-instalacao-e-laudo-spda', destination: '/laudo-spda-para-raios-sao-paulo', permanent: true },
      { source: '/servicos/sistema-de-alarme-de-incendio', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/servicos/sprinklers-chuveiros-automaticos', destination: '/sprinklers', permanent: true },
      { source: '/servicos/treinamento-de-brigada-de-incendio', destination: '/treinamento-brigada', permanent: true },
      { source: '/sistema-alarme-contra-incendio', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-alarme-deteccao-incendio', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-alarme-incendio', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-alarme-incendio-industrial', destination: '/alarme-de-incendio-galpao-industrial-sp', permanent: true },
      { source: '/sistema-alarme-incendio-predial', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-combate-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/sistema-combate-incendio-industrial', destination: '/projeto-incendio-galpao-industrial-avcb-sp', permanent: true },
      { source: '/sistema-combate-incendio-predial', destination: '/projetos-incendio', permanent: true },
      { source: '/sistema-combate-incendio-sprinkler', destination: '/sprinklers', permanent: true },
      { source: '/sistema-combate-incendios', destination: '/projetos-incendio', permanent: true },
      { source: '/sistema-deteccao-alarme-combate-incendio', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-deteccao-alarme-incendio', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-deteccao-alarme-incendio-projeto', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-deteccao-combate-incendio', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-deteccao-fumaca', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-deteccao-fumaca-calor', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-deteccao-precoce-incendio', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-detector-incendio', destination: '/alarme-incendio-sao-paulo', permanent: true },
      { source: '/sistema-hidrantes-combate-incendio', destination: '/hidrantes', permanent: true },
      { source: '/sistema-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/sistema-incendio-contra-sprinkler', destination: '/sprinklers', permanent: true },
      { source: '/sistema-incendio-empresa', destination: '/projetos-incendio', permanent: true },
      { source: '/sistema-incendio-industrial', destination: '/projeto-incendio-galpao-industrial-avcb-sp', permanent: true },
      { source: '/sistema-incendio-predial', destination: '/projetos-incendio', permanent: true },
      { source: '/sistema-incendio-spk', destination: '/sprinklers', permanent: true },
      { source: '/sistema-incendio-sprinkler', destination: '/sprinklers', permanent: true },
      { source: '/sistema-prevencao-combate-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/sistema-prevencao-incendio', destination: '/projetos-incendio', permanent: true },
      { source: '/sistema-protecao-incendio-chuveiros-automaticos', destination: '/sprinklers', permanent: true },
      { source: '/sistema-seguranca-sprinklers', destination: '/sprinklers', permanent: true },
      { source: '/sistema-sprinkler-incendio', destination: '/sprinklers', permanent: true },
      { source: '/sistema-sprinkler-instalacao', destination: '/sprinklers', permanent: true },
      { source: '/sistema-sprinkler-protecao-incendio', destination: '/sprinklers', permanent: true },
      { source: '/sistema-sprinklers', destination: '/sprinklers', permanent: true },
      { source: '/sistema-sprinklers-preco', destination: '/quanto-custa-sistema-sprinkler-sp', permanent: true },
      { source: '/sobre-nos', destination: '/sobre', permanent: true },
      { source: '/spda-laudo-tecnico', destination: '/laudo-spda-para-raios-sao-paulo', permanent: true },
      { source: '/suporte-consultoria-alf', destination: 'https://drd1.com.br/auto-de-licenca-de-funcionamento-sao-paulo', permanent: true },
      { source: '/treinamento-brigada-incendio', destination: '/treinamento-brigada', permanent: true },
      { source: '/treinamento-brigada-incendio-valor', destination: '/quanto-custa-brigada-incendio-sp', permanent: true },
      { source: '/treinamento-incendio', destination: '/treinamento-brigada', permanent: true },
      { source: '/valor-projeto-combate-incendio', destination: '/quanto-custa-projeto-incendio-sp', permanent: true },
      { source: '/valor-projeto-incendio', destination: '/quanto-custa-projeto-incendio-sp', permanent: true },
      { source: '/valor-projeto-preventivo-incendio', destination: '/quanto-custa-projeto-incendio-sp', permanent: true },
      { source: '/valor-treinamento-brigada-incendio', destination: '/quanto-custa-brigada-incendio-sp', permanent: true },
      // ===== 30/09/2026 — diagnóstico SEO: páginas com o mesmo título/H1 de outra URL =====
      { source: '/ptotep-sao-paulo', destination: '/ptotep', permanent: true },
      { source: '/projeto-pet', destination: '/regularizacao-de-eventos-sao-paulo', permanent: true },
      { source: '/servicos/projeto-pet-sp', destination: '/regularizacao-de-eventos-sao-paulo', permanent: true },
      { source: '/servicos/avcb-condominio-sao-paulo', destination: '/avcb-para-condominio-sao-paulo', permanent: true },
      { source: '/servicos/treinamento-brigada-incendio', destination: '/treinamento-brigada', permanent: true },
      // ===== 08/08/2026 — desduplicacao: /servicos/ e /blog/ vao para a raiz (versao completa) =====
      { source: '/blog/avcb-para-academia-sao-paulo', destination: '/avcb-para-academia-sao-paulo', permanent: true },
      { source: '/blog/avcb-para-creche-sao-paulo', destination: '/avcb-para-creche-sao-paulo', permanent: true },
      { source: '/blog/avcb-para-igreja-sao-paulo', destination: '/avcb-para-igreja-sao-paulo', permanent: true },
      { source: '/blog/avcb-para-padaria-sao-paulo', destination: '/avcb-para-padaria-sao-paulo', permanent: true },
      { source: '/blog/avcb-para-shopping-sao-paulo', destination: '/avcb-para-shopping-sao-paulo', permanent: true },
      { source: '/blog/avcb-vencido-o-que-fazer', destination: '/avcb-vencido-o-que-fazer', permanent: true },
      { source: '/servicos/alarme-de-incendio-comercial-escritorio-sp', destination: '/alarme-de-incendio-comercial-escritorio-sp', permanent: true },
      { source: '/servicos/alarme-de-incendio-escola-faculdade-sp', destination: '/alarme-de-incendio-escola-faculdade-sp', permanent: true },
      { source: '/servicos/alarme-de-incendio-galpao-industrial-sp', destination: '/alarme-de-incendio-galpao-industrial-sp', permanent: true },
      { source: '/servicos/alarme-de-incendio-hospital-clinica-sp', destination: '/alarme-de-incendio-hospital-clinica-sp', permanent: true },
      { source: '/servicos/alarme-de-incendio-para-condominio-sao-paulo', destination: '/alarme-de-incendio-para-condominio-sao-paulo', permanent: true },
      { source: '/servicos/avcb-casas-noturnas-boates-sao-paulo', destination: '/avcb-casas-noturnas-boates-sao-paulo', permanent: true },
      { source: '/servicos/avcb-comercial-escritorio-sao-paulo', destination: '/avcb-para-escritorio-sao-paulo', permanent: true },
      { source: '/servicos/avcb-consultorios-medicos-odontologicos-sao-paulo', destination: '/avcb-consultorios-medicos-odontologicos-sao-paulo', permanent: true },
      { source: '/servicos/avcb-farmacia-drogaria-sao-paulo', destination: '/avcb-farmacia-drogaria-sao-paulo', permanent: true },
      { source: '/servicos/avcb-galpao-industrial-sao-paulo', destination: '/avcb-galpao-industrial-sao-paulo', permanent: true },
      { source: '/servicos/avcb-hospital-clinica-sao-paulo', destination: '/avcb-hospital-clinica-sao-paulo', permanent: true },
      { source: '/servicos/avcb-hostel-sao-paulo', destination: '/avcb-hostel-sao-paulo', permanent: true },
      { source: '/servicos/avcb-motel-sao-paulo', destination: '/avcb-motel-sao-paulo', permanent: true },
      { source: '/servicos/avcb-para-academia-sao-paulo', destination: '/avcb-para-academia-sao-paulo', permanent: true },
      { source: '/servicos/avcb-para-casa-de-repouso-sao-paulo', destination: '/avcb-para-casa-de-repouso-sao-paulo', permanent: true },
      { source: '/servicos/avcb-para-creche-sao-paulo', destination: '/avcb-para-creche-sao-paulo', permanent: true },
      { source: '/servicos/avcb-para-escola-sao-paulo', destination: '/avcb-para-escola-sao-paulo', permanent: true },
      { source: '/servicos/avcb-para-escritorio-sao-paulo', destination: '/avcb-para-escritorio-sao-paulo', permanent: true },
      { source: '/servicos/avcb-para-igreja-sao-paulo', destination: '/avcb-para-igreja-sao-paulo', permanent: true },
      { source: '/servicos/avcb-para-padaria-sao-paulo', destination: '/avcb-para-padaria-sao-paulo', permanent: true },
      { source: '/servicos/avcb-para-shopping-sao-paulo', destination: '/avcb-para-shopping-sao-paulo', permanent: true },
      { source: '/servicos/avcb-posto-combustivel-sao-paulo', destination: '/avcb-posto-combustivel-sao-paulo', permanent: true },
      { source: '/servicos/avcb-restaurante-sao-paulo', destination: '/avcb-restaurante-sao-paulo', permanent: true },
      { source: '/servicos/avcb-salao-de-festas-sao-paulo', destination: '/avcb-salao-de-festas-sao-paulo', permanent: true },
      { source: '/servicos/avcb-supermercado-sao-paulo', destination: '/avcb-supermercado-sao-paulo', permanent: true },
      { source: '/servicos/laudo-estanqueidade-gas-sao-paulo', destination: '/laudo-estanqueidade-gas-sao-paulo', permanent: true },
      { source: '/servicos/projeto-escada-pressurizada-avcb-sao-paulo', destination: '/projeto-escada-pressurizada-avcb-sao-paulo', permanent: true },
      { source: '/servicos/renovacao-avcb-condominio-sao-paulo', destination: '/renovacao-avcb-condominio-sao-paulo', permanent: true },
      // 25/09/2026 — páginas duplicadas unificadas: cada origem tratava do mesmo assunto que o destino.
      // Mantém a página que o Google já indexava (ou a de nome mais claro) e soma a força das duas.
      { source: '/sistema-de-hidrantes-para-hotel-sao-paulo', destination: '/sistema-hidrante-hotel-avcb-sp', permanent: true },
      { source: '/sistema-de-sprinkler-para-hotel-sao-paulo', destination: '/sistema-sprinkler-hotel-avcb-sp', permanent: true },
      { source: '/sistema-de-hidrantes-para-hospital-sao-paulo', destination: '/sistema-hidrante-hospital-avcb-sp', permanent: true },
      { source: '/sistema-de-sprinkler-para-hospital-sao-paulo', destination: '/sistema-sprinkler-hospital-avcb-sp', permanent: true },
      { source: '/avcb-escola-faculdade-sao-paulo', destination: '/avcb-para-escola-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-escola-sao-paulo', destination: '/alvara-bombeiro-escola-faculdade-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-escola-sao-paulo', destination: '/laudo-bombeiro-escola-faculdade-sao-paulo', permanent: true },
      { source: '/avcb-comercial-escritorio-sao-paulo', destination: '/avcb-para-escritorio-sao-paulo', permanent: true },
      { source: '/alvara-bombeiro-restaurante-sao-paulo', destination: '/alvara-bombeiro-bar-restaurante-sao-paulo', permanent: true },
      { source: '/laudo-bombeiro-restaurante-sao-paulo', destination: '/laudo-bombeiro-bar-restaurante-sao-paulo', permanent: true },
      { source: '/renovacao-avcb-bares-restaurantes-sao-paulo', destination: '/renovacao-avcb-restaurante-sao-paulo', permanent: true },
      { source: '/avcb-pousada-sao-paulo', destination: '/avcb-hoteis-pousadas-sao-paulo', permanent: true },
    ];
  },
};

export default nextConfig;
